beer_to_beer_core_homepage:
    path:     /
    defaults: { _controller: BeerToBeerCoreBundle:Default:index }

btb_api_business:
    path:     /api/business
    defaults: { _controller: BeerToBeerCoreBundle:Api:business }
    requirements:
        _method: GET

btb_api_business_propose:
    path:     /api/business
    defaults: { _controller: BeerToBeerCoreBundle:Api:proposeBusiness }
    requirements:
        _method: POST

btb_api_business_id:
    path:     /api/business/{id}
    defaults: { _controller: BeerToBeerCoreBundle:Api:getBusinessFromId }
    requirements:
        id: \d+
        _method: GET

btb_api_update_business_id:
    path:     /api/business/{id}
    defaults: { _controller: BeerToBeerCoreBundle:Api:updateBusiness }
    requirements:
        id: \d+
        _method: PUT

btb_api_beers:
    path:     /api/beer
    defaults: { _controller: BeerToBeerCoreBundle:Api:getAllBeers }
    requirements:
        _method: GET