parameters:
#    beer_to_beer_core.example.class: BeerToBeer\CoreBundle\Example

services:
#    beer_to_beer_core.example:
#        class: %beer_to_beer_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
